// vendored from @patternmode/swatch@4.1.3 — generated by scripts/build-registry.mjs; do not hand-edit.
export {
  type DistributionBarSegment,
  type DistributionBarSegmentUpdate,
  type DistributionSegment,
  type DistributionSegmentUpdate,
  getDerivedDistributionPercentage,
  getDistributionBoundaryPercent,
  getDistributionTotal,
  moveDistributionBoundary,
  removeDistributionSegment,
  updateDistributionSegment,
} from "./distribution-math";
export { DistributionSegmentLegend, DistributionSegments } from "./distribution-parts";
