/**
 * Keep Patternmode's lint 0.5 native policy while using the TS7-only lint 3 toolchain.
 * These explicit deltas were compared against the previous Core/Next presets,
 * including Oxlint's default warning severities, rather than disabling whole plugins.
 * GitHub/SonarJS are intentionally retired; their TS6-backed plugins are not loaded.
 * New anti-slop and test-style policy needs a separate, deliberate migration.
 */
import core from "@howells/lint/oxlint/core";
import next from "@howells/lint/oxlint/next";

const coreCompatibility = {
  overrides: [
    {
      files: ["**/*.{test,spec}.{ts,tsx,js,jsx}", "**/__tests__/**/*.{ts,tsx,js,jsx}"],
      // Preserve the previous 12 explicit errors and 9 default warnings in tests.
      rules: {
        "vitest/consistent-each-for": "off",
        "vitest/consistent-test-filename": "off",
        "vitest/consistent-vitest-vi": "off",
        "vitest/expect-expect": "warn",
        "vitest/max-expects": "off",
        "vitest/max-nested-describe": "off",
        "vitest/no-alias-methods": "off",
        "vitest/no-conditional-expect": "warn",
        "vitest/no-duplicate-hooks": "off",
        "vitest/no-interpolation-in-snapshots": "off",
        "vitest/no-large-snapshots": "off",
        "vitest/no-restricted-matchers": "off",
        "vitest/no-restricted-vi-methods": "off",
        "vitest/no-test-prefixes": "off",
        "vitest/no-test-return-statement": "off",
        "vitest/no-unneeded-async-expect-function": "off",
        "vitest/padding-around-after-all-blocks": "off",
        "vitest/padding-around-test-blocks": "off",
        "vitest/prefer-called-exactly-once-with": "off",
        "vitest/prefer-called-once": "off",
        "vitest/prefer-called-with": "off",
        "vitest/prefer-comparison-matcher": "off",
        "vitest/prefer-describe-function-title": "off",
        "vitest/prefer-each": "off",
        "vitest/prefer-equality-matcher": "off",
        "vitest/prefer-expect-resolves": "off",
        "vitest/prefer-expect-type-of": "off",
        "vitest/prefer-hooks-in-order": "off",
        "vitest/prefer-hooks-on-top": "off",
        "vitest/prefer-import-in-mock": "off",
        "vitest/prefer-importing-vitest-globals": "off",
        "vitest/prefer-mock-promise-shorthand": "off",
        "vitest/prefer-mock-return-shorthand": "off",
        "vitest/prefer-snapshot-hint": "warn",
        "vitest/prefer-spy-on": "off",
        "vitest/prefer-strict-equal": "off",
        "vitest/prefer-to-be": "off",
        "vitest/prefer-to-be-falsy": "off",
        "vitest/prefer-to-be-object": "off",
        "vitest/prefer-to-be-truthy": "off",
        "vitest/prefer-to-contain": "off",
        "vitest/prefer-to-have-been-called-times": "off",
        "vitest/prefer-to-have-length": "off",
        "vitest/prefer-todo": "off",
        "vitest/require-awaited-expect-poll": "warn",
        "vitest/require-local-test-context-for-concurrent-snapshots": "warn",
        "vitest/require-mock-type-parameters": "warn",
        "vitest/require-to-throw-message": "warn",
        "vitest/require-top-level-describe": "off",
        "vitest/valid-title": "warn",
        "vitest/warn-todo": "warn",
      },
    },
  ],
  rules: {
    "anti-slop/no-chained-type-assertions": "off",
    "anti-slop/no-conditional-empty-object-spread": "off",
    "anti-slop/no-known-value-widening": "off",
    "anti-slop/no-module-mocking": "off",
    "anti-slop/no-object-parameters": "off",
    "anti-slop/no-reflect-apply": "off",
    "anti-slop/no-reflect-get": "off",
    "anti-slop/no-runtime-typeof": "off",
    "anti-slop/no-shape-in-symbol-names": "off",
    "anti-slop/no-unknown-parameters": "off",
    "anti-slop/no-unknown-returns": "off",
    "anti-slop/no-unknown-type-aliases": "off",
    "anti-slop/no-unsafe-dictionary-type": "off",
    "anti-slop/no-widen-then-assert": "off",
    "anti-slop/require-safety-comment-for-type-assertion": "off",
    "jsdoc/no-blank-blocks": "off",
    "one-var": "off",
    "typescript/consistent-indexed-object-style": "error",
    "unicorn/no-immediate-mutation": "error",
  },
} as const;

// Lint 3's native Next refresh rule retains the framework export allowlist;
// the newer React Doctor implementation no longer understands those exports.
// These newly split compiler categories report skipped optimization, not invalid
// React behavior. Keep them visible without rewriting deliberate effect triggers,
// supported JS syntax, or TanStack Virtual during a toolchain migration.
const nextCompatibility = {
  rules: {
    "anti-slop/no-chained-type-assertions": "off",
    "anti-slop/no-conditional-empty-object-spread": "off",
    "anti-slop/no-known-value-widening": "off",
    "anti-slop/no-module-mocking": "off",
    "anti-slop/no-object-parameters": "off",
    "anti-slop/no-reflect-apply": "off",
    "anti-slop/no-reflect-get": "off",
    "anti-slop/no-runtime-typeof": "off",
    "anti-slop/no-shape-in-symbol-names": "off",
    "anti-slop/no-unknown-parameters": "off",
    "anti-slop/no-unknown-returns": "off",
    "anti-slop/no-unknown-type-aliases": "off",
    "anti-slop/no-unsafe-dictionary-type": "off",
    "anti-slop/no-widen-then-assert": "off",
    "anti-slop/require-safety-comment-for-type-assertion": "off",
    "getter-return": "off",
    "id-denylist": "off",
    "jsdoc/no-blank-blocks": "off",
    "jsx-a11y/alt-text": "off",
    "jsx-a11y/anchor-ambiguous-text": "off",
    "jsx-a11y/anchor-has-content": "off",
    "jsx-a11y/anchor-is-valid": "off",
    "jsx-a11y/aria-activedescendant-has-tabindex": "off",
    "jsx-a11y/aria-props": "off",
    "jsx-a11y/aria-proptypes": "off",
    "jsx-a11y/aria-role": "off",
    "jsx-a11y/aria-unsupported-elements": "off",
    "jsx-a11y/autocomplete-valid": "off",
    "jsx-a11y/click-events-have-key-events": "off",
    "jsx-a11y/heading-has-content": "off",
    "jsx-a11y/html-has-lang": "off",
    "jsx-a11y/iframe-has-title": "off",
    "jsx-a11y/img-redundant-alt": "off",
    "jsx-a11y/label-has-associated-control": "off",
    "jsx-a11y/lang": "off",
    "jsx-a11y/media-has-caption": "off",
    "jsx-a11y/mouse-events-have-key-events": "off",
    "jsx-a11y/no-access-key": "off",
    "jsx-a11y/no-aria-hidden-on-focusable": "off",
    "jsx-a11y/no-distracting-elements": "off",
    "jsx-a11y/no-noninteractive-tabindex": "off",
    "jsx-a11y/no-redundant-roles": "off",
    "jsx-a11y/no-static-element-interactions": "off",
    "jsx-a11y/prefer-tag-over-role": "off",
    "jsx-a11y/role-has-required-aria-props": "off",
    "jsx-a11y/role-supports-aria-props": "off",
    "jsx-a11y/scope": "off",
    "jsx-a11y/tabindex-no-positive": "off",
    "nextjs/google-font-display": "off",
    "nextjs/google-font-preconnect": "off",
    "nextjs/inline-script-id": "off",
    "nextjs/next-script-for-ga": "off",
    "nextjs/no-assign-module-variable": "off",
    "nextjs/no-async-client-component": "off",
    "nextjs/no-before-interactive-script-outside-document": "off",
    "nextjs/no-css-tags": "off",
    "nextjs/no-document-import-in-page": "off",
    "nextjs/no-duplicate-head": "off",
    "nextjs/no-head-element": "off",
    "nextjs/no-head-import-in-document": "off",
    "nextjs/no-html-link-for-pages": "off",
    "nextjs/no-img-element": "off",
    "nextjs/no-page-custom-font": "off",
    "nextjs/no-script-component-in-head": "off",
    "nextjs/no-styled-jsx-in-document": "off",
    "nextjs/no-sync-scripts": "off",
    "nextjs/no-title-in-document-head": "off",
    "nextjs/no-typos": "off",
    "nextjs/no-unwanted-polyfillio": "off",
    "no-await-in-loop": "off",
    "no-unreachable": "off",
    "no-unreachable-loop": "off",
    "node/exports-style": "off",
    "node/no-mixed-requires": "off",
    "node/no-sync": "off",
    "node/no-top-level-await": "off",
    "one-var": "off",
    "oxc/bad-match-all-arg": "off",
    "oxc/branches-sharing-code": "off",
    "react-doctor/activity-wraps-effect-heavy-subtree": "warn",
    "react-doctor/advanced-event-handler-refs": "warn",
    "react-doctor/async-await-in-loop": "warn",
    "react-doctor/async-defer-await": "warn",
    "react-doctor/async-parallel": "warn",
    "react-doctor/auth-token-in-web-storage": "off",
    "react-doctor/client-localstorage-no-version": "warn",
    "react-doctor/client-passive-event-listeners": "warn",
    "react-doctor/dialog-has-accessible-name": "off",
    "react-doctor/hooks-no-nan-in-deps": "warn",
    "react-doctor/html-no-invalid-paragraph-child": "warn",
    "react-doctor/html-no-invalid-table-nesting": "warn",
    "react-doctor/html-no-nested-interactive": "warn",
    "react-doctor/jotai-derived-atom-returns-fresh-object": "warn",
    "react-doctor/jotai-tq-use-raw-query-atom": "warn",
    "react-doctor/js-async-reduce-without-awaited-acc": "warn",
    "react-doctor/js-batch-dom-css": "warn",
    "react-doctor/js-cache-property-access": "warn",
    "react-doctor/js-cache-storage": "warn",
    "react-doctor/js-combine-iterations": "warn",
    "react-doctor/js-early-exit": "warn",
    "react-doctor/js-flatmap-filter": "warn",
    "react-doctor/js-hoist-intl": "warn",
    "react-doctor/js-hoist-regexp": "warn",
    "react-doctor/js-index-maps": "warn",
    "react-doctor/js-length-check-first": "warn",
    "react-doctor/js-min-max-loop": "warn",
    "react-doctor/js-set-map-lookups": "warn",
    "react-doctor/js-tosorted-immutable": "warn",
    "react-doctor/nextjs-image-missing-sizes": "warn",
    "react-doctor/nextjs-inline-script-missing-id": "warn",
    "react-doctor/nextjs-missing-metadata": "warn",
    "react-doctor/nextjs-no-a-element": "warn",
    "react-doctor/nextjs-no-client-fetch-for-server-data": "warn",
    "react-doctor/nextjs-no-client-side-redirect": "warn",
    "react-doctor/nextjs-no-css-link": "warn",
    "react-doctor/nextjs-no-edge-og-runtime": "warn",
    "react-doctor/nextjs-no-font-link": "warn",
    "react-doctor/nextjs-no-google-analytics-script": "warn",
    "react-doctor/nextjs-no-img-element": "warn",
    "react-doctor/nextjs-no-native-script": "warn",
    "react-doctor/nextjs-no-polyfill-script": "warn",
    "react-doctor/nextjs-no-redirect-in-try-catch": "warn",
    "react-doctor/nextjs-no-use-search-params-without-suspense": "warn",
    "react-doctor/nextjs-no-vercel-og-import": "warn",
    "react-doctor/no-array-index-as-key": "warn",
    "react-doctor/no-async-effect-callback": "off",
    "react-doctor/no-barrel-import": "warn",
    "react-doctor/no-call-component-as-function": "off",
    "react-doctor/no-cascading-set-state": "warn",
    "react-doctor/no-chain-state-updates": "warn",
    "react-doctor/no-create-ref-in-function-component": "off",
    "react-doctor/no-derived-state": "warn",
    "react-doctor/no-derived-state-effect": "warn",
    "react-doctor/no-derived-useState": "warn",
    "react-doctor/no-direct-state-mutation": "warn",
    "react-doctor/no-document-start-view-transition": "warn",
    "react-doctor/no-document-write": "off",
    "react-doctor/no-dynamic-import-path": "warn",
    "react-doctor/no-effect-chain": "warn",
    "react-doctor/no-effect-event-handler": "warn",
    "react-doctor/no-event-handler": "warn",
    "react-doctor/no-event-trigger-state": "warn",
    "react-doctor/no-fetch-in-effect": "warn",
    "react-doctor/no-flush-sync": "warn",
    "react-doctor/no-full-lodash-import": "warn",
    "react-doctor/no-gray-on-colored-background": "warn",
    "react-doctor/no-img-lazy-with-high-fetchpriority": "off",
    "react-doctor/no-initialize-state": "warn",
    "react-doctor/no-inline-bounce-easing": "warn",
    "react-doctor/no-inline-exhaustive-style": "warn",
    "react-doctor/no-inline-prop-on-memo-component": "warn",
    "react-doctor/no-json-parse-stringify-clone": "off",
    "react-doctor/no-large-animated-blur": "warn",
    "react-doctor/no-layout-transition-inline": "warn",
    "react-doctor/no-long-transition-duration": "warn",
    "react-doctor/no-many-boolean-props": "warn",
    "react-doctor/no-mirror-prop-effect": "warn",
    "react-doctor/no-moment": "warn",
    "react-doctor/no-outline-none": "warn",
    "react-doctor/no-pass-data-to-parent": "warn",
    "react-doctor/no-pass-live-state-to-parent": "warn",
    "react-doctor/no-permanent-will-change": "warn",
    "react-doctor/no-polymorphic-children": "warn",
    "react-doctor/no-prevent-default": "warn",
    "react-doctor/no-prop-callback-in-effect": "warn",
    "react-doctor/no-react-dom-deprecated-apis": "warn",
    "react-doctor/no-react19-deprecated-apis": "warn",
    "react-doctor/no-render-in-render": "warn",
    "react-doctor/no-render-prop-children": "warn",
    "react-doctor/no-reset-all-state-on-prop-change": "warn",
    "react-doctor/no-scale-from-zero": "warn",
    "react-doctor/no-secrets-in-client-code": "warn",
    "react-doctor/no-self-updating-effect": "warn",
    "react-doctor/no-set-state-in-render": "warn",
    "react-doctor/no-string-false-on-boolean-attribute": "off",
    "react-doctor/no-sync-xhr": "off",
    "react-doctor/no-tiny-text": "warn",
    "react-doctor/no-transition-all": "warn",
    "react-doctor/no-uncontrolled-input": "warn",
    "react-doctor/no-undeferred-third-party": "warn",
    "react-doctor/no-usememo-simple-expression": "warn",
    "react-doctor/only-export-components": "warn",
    "react-doctor/prefer-dynamic-import": "warn",
    "react-doctor/prefer-explicit-variants": "warn",
    "react-doctor/prefer-html-dialog": "warn",
    "react-doctor/prefer-module-scope-pure-function": "warn",
    "react-doctor/prefer-module-scope-static-value": "warn",
    "react-doctor/prefer-stable-empty-fallback": "warn",
    "react-doctor/prefer-use-effect-event": "warn",
    "react-doctor/prefer-use-sync-external-store": "warn",
    "react-doctor/prefer-useReducer": "warn",
    "react-doctor/query-destructure-result": "off",
    "react-doctor/query-mutation-missing-invalidation": "off",
    "react-doctor/query-no-query-in-effect": "off",
    "react-doctor/query-no-rest-destructuring": "off",
    "react-doctor/query-no-usequery-for-mutation": "off",
    "react-doctor/query-no-void-query-fn": "off",
    "react-doctor/query-stable-query-client": "off",
    "react-doctor/react-compiler-no-manual-memoization": "warn",
    "react-doctor/redux-useselector-inline-derivation": "warn",
    "react-doctor/redux-useselector-returns-new-collection": "warn",
    "react-doctor/rendering-animate-svg-wrapper": "warn",
    "react-doctor/rendering-conditional-render": "warn",
    "react-doctor/rendering-hoist-jsx": "warn",
    "react-doctor/rendering-hydration-mismatch-time": "warn",
    "react-doctor/rendering-hydration-no-flicker": "warn",
    "react-doctor/rendering-script-defer-async": "warn",
    "react-doctor/rendering-svg-precision": "warn",
    "react-doctor/rendering-usetransition-loading": "warn",
    "react-doctor/rerender-defer-reads-hook": "warn",
    "react-doctor/rerender-derived-state-from-hook": "warn",
    "react-doctor/rerender-functional-setstate": "warn",
    "react-doctor/rerender-lazy-ref-init": "warn",
    "react-doctor/rerender-lazy-state-init": "warn",
    "react-doctor/rerender-memo-before-early-return": "warn",
    "react-doctor/rerender-memo-with-default-value": "warn",
    "react-doctor/rerender-state-only-in-handlers": "warn",
    "react-doctor/rerender-transitions-scroll": "warn",
    "react-doctor/server-after-nonblocking": "warn",
    "react-doctor/server-cache-with-object-literal": "warn",
    "react-doctor/server-dedup-props": "warn",
    "react-doctor/server-fetch-without-revalidate": "warn",
    "react-doctor/server-hoist-static-io": "warn",
    "react-doctor/server-sequential-independent-await": "warn",
    "react-doctor/use-lazy-motion": "warn",
    "react-doctor/zod-v4-no-deprecated-error-apis": "warn",
    "react-doctor/zod-v4-no-deprecated-error-customization": "warn",
    "react-doctor/zod-v4-no-deprecated-schema-apis": "warn",
    "react-doctor/zod-v4-prefer-top-level-string-formats": "warn",
    "react-perf/jsx-no-new-function-as-prop": "off",
    "react/button-has-type": "warn",
    "react/capitalized-calls": "off",
    "react/checked-requires-onchange-or-readonly": "warn",
    "react/display-name": "off",
    "react/error-boundaries": "off",
    "react/exhaustive-deps": "warn",
    "react/exhaustive-effect-dependencies": "off",
    "react/forbid-dom-props": "warn",
    "react/forbid-elements": "warn",
    "react/forward-ref-uses-ref": "warn",
    "react/function-component-definition": "off",
    "react/globals": "off",
    "react/hook-use-state": "off",
    "react/hooks": "off",
    "react/iframe-missing-sandbox": "warn",
    "react/immutability": "off",
    "react/incompatible-library": "off",
    "react/invariant": "off",
    "react/jsx-curly-brace-presence": "off",
    "react/jsx-fragments": "off",
    "react/jsx-handler-names": "off",
    "react/jsx-no-comment-textnodes": "warn",
    "react/jsx-no-constructed-context-values": "warn",
    "react/jsx-no-literals": "off",
    "react/jsx-no-target-blank": "warn",
    "react/jsx-no-useless-fragment": "off",
    "react/jsx-pascal-case": "off",
    "react/jsx-props-no-spread-multi": "warn",
    "react/memo-dependencies": "off",
    "react/no-array-index-key": "off",
    "react/no-children-prop": "warn",
    "react/no-clone-element": "off",
    "react/no-danger": "warn",
    "react/no-deriving-state-in-effects": "off",
    "react/no-did-mount-set-state": "warn",
    "react/no-did-update-set-state": "warn",
    "react/no-find-dom-node": "warn",
    "react/no-is-mounted": "warn",
    "react/no-namespace": "warn",
    "react/no-react-children": "off",
    "react/no-redundant-should-component-update": "warn",
    "react/no-render-return-value": "warn",
    "react/no-set-state": "off",
    "react/no-string-refs": "warn",
    "react/no-this-in-sfc": "warn",
    "react/no-unescaped-entities": "off",
    "react/no-unsafe": "warn",
    "react/no-will-update-set-state": "warn",
    "react/only-export-components": "off",
    "react/prefer-es6-class": "off",
    "react/prefer-function-component": "off",
    "react/preserve-manual-memoization": "off",
    "react/purity": "off",
    "react/refs": "off",
    "react/rule-suppression": "off",
    "react/self-closing-comp": "off",
    "react/set-state-in-effect": "off",
    "react/set-state-in-render": "off",
    "react/state-in-constructor": "off",
    "react/static-components": "off",
    "react/style-prop-object": "warn",
    "react/syntax": "off",
    "react/todo": "off",
    "react/unsupported-syntax": "off",
    "react/use-memo": "off",
    "react/void-dom-elements-no-children": "warn",
    "react/void-use-memo": "off",
    "require-await": "error",
    "typescript/consistent-indexed-object-style": "error",
    "unicorn/explicit-timer-delay": "off",
    "unicorn/max-nested-calls": "off",
    "unicorn/no-array-fill-with-reference-type": "off",
    "unicorn/no-confusing-array-with": "off",
    "unicorn/no-immediate-mutation": "error",
    "unicorn/prefer-export-from": "off",
    "unicorn/prefer-number-coercion": "off",
    "unicorn/prefer-single-call": "off",
  },
} as const;

/** Patch inherited declarations in place: Oxlint applies those test overrides before root overrides. */
const preservePolicy = (
  preset: typeof core,
  rules: Record<string, "error" | "off" | "warn">,
): typeof core => {
  const patch = (existing: typeof core.rules): typeof core.rules => {
    const result = { ...existing };
    for (const [name, severity] of Object.entries(rules)) {
      if (name in result) {
        result[name] = severity;
      }
    }
    for (const [name, severity] of Object.entries(coreCompatibility.overrides[0].rules)) {
      if (name in result) {
        result[name] = severity;
      }
    }
    return result;
  };
  return {
    ...preset,
    extends: preset.extends?.map((entry) =>
      typeof entry === "string" ? entry : preservePolicy(entry, rules),
    ),
    overrides: preset.overrides?.map((override) => ({ ...override, rules: patch(override.rules) })),
    rules: patch(preset.rules),
  };
};

export const compatibleCore = preservePolicy(core, coreCompatibility.rules);
export const compatibleNext = preservePolicy(next, {
  ...coreCompatibility.rules,
  ...nextCompatibility.rules,
});
