// vendored from @patternmode/swatch@4.1.3 — generated by scripts/build-registry.mjs; do not hand-edit.
export { DistributionDisplay, type DistributionDisplayProps } from "./distribution-display-root";
